site_name: Blog
site_url: https://yaomengsi.github.io/blog
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.indexes
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
# nav:
#   - home:
#       - index.md
#   - Blog:
#       - blog/index.md
#